# Generated by Django 5.0.2 on 2024-02-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('Admin_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('Admin_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Admin_table',
            },
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('District_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('District_Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'District_table',
            },
        ),
        migrations.CreateModel(
            name='MainCategoryModel',
            fields=[
                ('Main_category_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('Main_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'MainCategory_table',
            },
        ),
        migrations.CreateModel(
            name='OfferEventModel',
            fields=[
                ('Offer_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('Offer_Name', models.CharField(max_length=50)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
            options={
                'db_table': 'Offer_Event_table',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('Product_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Product_title', models.CharField(max_length=50)),
                ('Product_description', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'Product_table',
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('City_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('City_Name', models.CharField(max_length=50)),
                ('District_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.districtmodel')),
            ],
            options={
                'db_table': 'City_table',
            },
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('image_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='images/')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AdminApp.productmodel')),
            ],
            options={
                'db_table': 'Product_image_table',
            },
        ),
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('Event_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('Discount', models.IntegerField()),
                ('Offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.offereventmodel')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.productmodel')),
            ],
            options={
                'db_table': 'Offer_table',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('Sub_category_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('Sub_category', models.CharField(max_length=50)),
                ('Main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.maincategorymodel')),
            ],
            options={
                'db_table': 'SubCategory_table',
            },
        ),
        migrations.CreateModel(
            name='SubSubCategoryModel',
            fields=[
                ('Sub_sub_category_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('Sub_sub_category', models.CharField(max_length=50)),
                ('Sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.subcategorymodel')),
            ],
            options={
                'db_table': 'Sub_sub_category_table',
            },
        ),
        migrations.CreateModel(
            name='VariantProductModel',
            fields=[
                ('Variant_product_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('Variant_product_name', models.CharField(max_length=50)),
                ('Size', models.IntegerField()),
                ('Quantity', models.CharField(max_length=50, null=True)),
                ('Color', models.CharField(max_length=50)),
                ('Occasion', models.CharField(max_length=50)),
                ('Neck', models.CharField(max_length=50)),
                ('Bottom_Fabric', models.CharField(max_length=50)),
                ('Top_type', models.CharField(max_length=50)),
                ('Sleeve_Length', models.CharField(max_length=50)),
                ('Top_Fabric', models.CharField(max_length=50)),
                ('Bottom_Type', models.CharField(max_length=50)),
                ('Bottom_Pattern', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.productmodel')),
            ],
            options={
                'db_table': 'Variant_Product_table',
            },
        ),
    ]
