# Generated by Django 5.0.2 on 2024-02-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_productmodel_main_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('Brand_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('Brand_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Brand_table',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='Brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandmodel'),
        ),
    ]
