# Generated by Django 5.0.2 on 2024-02-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_brandmodel_productmodel_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offereventmodel',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
