# Generated by Django 5.0.2 on 2024-02-20 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewratingmodel',
            name='Product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.productmodel'),
        ),
    ]
