# Generated by Django 5.0.2 on 2024-03-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_usermodel_viewed_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='viewed_products',
        ),
    ]
